//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Витрати_ГСМ_в_годину
    {
        public int Id_ВитратГСМ { get; set; }
        public int Id_Механізма { get; set; }
        public int Id_Палива { get; set; }
        public Nullable<decimal> Витрати_ГСМ_переїзд_кг_ч { get; set; }
        public Nullable<decimal> Витрати_ГСМ_зупинка_кг_ч { get; set; }
    
        public virtual Вид_ГСМ Вид_ГСМ { get; set; }
        public virtual Механізми Механізми { get; set; }
    }
}
