//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кубатурник
    {
        public int Id { get; set; }
        public int Диаметр { get; set; }
        public decimal C1 { get; set; }
        public decimal C1_1 { get; set; }
        public decimal C1_2 { get; set; }
        public decimal C1_3 { get; set; }
        public decimal C1_4 { get; set; }
        public decimal C1_5 { get; set; }
        public decimal C1_6 { get; set; }
        public decimal C1_7 { get; set; }
        public decimal C1_8 { get; set; }
        public decimal C1_9 { get; set; }
        public decimal C2 { get; set; }
        public decimal C2_1 { get; set; }
        public decimal C2_2 { get; set; }
        public decimal C2_25 { get; set; }
        public decimal C2_3 { get; set; }
        public decimal C2_4 { get; set; }
        public decimal C2_5 { get; set; }
        public decimal C2_6 { get; set; }
        public decimal C2_7 { get; set; }
        public decimal C2_75 { get; set; }
        public decimal C2_8 { get; set; }
        public decimal C2_9 { get; set; }
        public decimal C3 { get; set; }
        public decimal C3_1 { get; set; }
        public decimal C3_2 { get; set; }
        public decimal C3_25 { get; set; }
        public decimal C3_3 { get; set; }
        public decimal C3_4 { get; set; }
        public decimal C3_5 { get; set; }
        public decimal C3_6 { get; set; }
        public decimal C3_7 { get; set; }
        public decimal C3_75 { get; set; }
        public decimal C3_8 { get; set; }
        public decimal C3_9 { get; set; }
        public decimal C4 { get; set; }
        public decimal C4_1 { get; set; }
        public decimal C4_2 { get; set; }
        public decimal C4_25 { get; set; }
        public decimal C4_3 { get; set; }
        public decimal C4_4 { get; set; }
        public decimal C4_5 { get; set; }
        public decimal C4_6 { get; set; }
        public decimal C4_7 { get; set; }
        public decimal C4_75 { get; set; }
        public decimal C4_8 { get; set; }
        public decimal C4_9 { get; set; }
        public decimal C5 { get; set; }
        public decimal C5_1 { get; set; }
        public decimal C5_2 { get; set; }
        public decimal C5_25 { get; set; }
        public decimal C5_3 { get; set; }
        public decimal C5_4 { get; set; }
        public decimal C5_5 { get; set; }
        public decimal C5_6 { get; set; }
        public decimal C5_7 { get; set; }
        public decimal C5_75 { get; set; }
        public decimal C5_8 { get; set; }
        public decimal C5_9 { get; set; }
        public decimal C6 { get; set; }
        public decimal C6_1 { get; set; }
        public decimal C6_2 { get; set; }
        public decimal C6_25 { get; set; }
        public decimal C6_3 { get; set; }
        public decimal C6_4 { get; set; }
        public decimal C6_5 { get; set; }
        public decimal C6_6 { get; set; }
        public decimal C6_7 { get; set; }
        public decimal C6_75 { get; set; }
        public decimal C6_8 { get; set; }
        public decimal C6_9 { get; set; }
        public decimal C7 { get; set; }
        public decimal C7_1 { get; set; }
        public decimal C7_2 { get; set; }
        public decimal C7_25 { get; set; }
        public decimal C7_3 { get; set; }
        public decimal C7_4 { get; set; }
        public decimal C7_5 { get; set; }
        public decimal C7_6 { get; set; }
        public decimal C7_7 { get; set; }
        public decimal C7_75 { get; set; }
        public decimal C7_8 { get; set; }
        public decimal C7_9 { get; set; }
        public decimal C8 { get; set; }
        public decimal C8_1 { get; set; }
        public decimal C8_2 { get; set; }
        public decimal C8_25 { get; set; }
        public decimal C8_3 { get; set; }
        public decimal C8_4 { get; set; }
        public decimal C8_5 { get; set; }
        public decimal C8_6 { get; set; }
        public decimal C8_7 { get; set; }
        public decimal C8_75 { get; set; }
        public decimal C8_8 { get; set; }
        public decimal C8_9 { get; set; }
        public decimal C9 { get; set; }
        public decimal C9_1 { get; set; }
        public decimal C9_2 { get; set; }
        public decimal C9_25 { get; set; }
        public decimal C9_3 { get; set; }
        public decimal C9_4 { get; set; }
        public decimal C9_5 { get; set; }
        public decimal C10 { get; set; }
        public decimal C10_5 { get; set; }
        public decimal C11 { get; set; }
        public decimal C11_5 { get; set; }
        public decimal C12 { get; set; }
        public decimal C12_5 { get; set; }
        public decimal C13 { get; set; }
        public decimal C13_5 { get; set; }
    }
}
