//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Робітники
    {
        public int Id_Робітника { get; set; }
        public string П_І_Б { get; set; }
        public string Професія { get; set; }
        public Nullable<int> Тарифний_розряд { get; set; }
        public Nullable<int> Категорія { get; set; }
    }
}
