//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вид_робіт_Сортименти
    {
        public int Id_Сортимент { get; set; }
        public string Сортимент { get; set; }
        public decimal C0_05 { get; set; }
        public decimal C0_08 { get; set; }
        public decimal C0_12 { get; set; }
        public decimal C0_22 { get; set; }
        public decimal C0_36 { get; set; }
        public decimal C0_54 { get; set; }
        public decimal C0_76 { get; set; }
        public decimal C1_02 { get; set; }
        public decimal C1_29 { get; set; }
        public decimal C1_61 { get; set; }
    }
}
