//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вид_ГСМ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вид_ГСМ()
        {
            this.Витрати_ГСМ = new HashSet<Витрати_ГСМ>();
            this.Витрати_ГСМ_в_годину = new HashSet<Витрати_ГСМ_в_годину>();
        }
    
        public int Id_Палива { get; set; }
        public string Вид_ГСМ1 { get; set; }
        public decimal Ціні_палива { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Витрати_ГСМ> Витрати_ГСМ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Витрати_ГСМ_в_годину> Витрати_ГСМ_в_годину { get; set; }
    }
}
