//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вид_робіт_Сортименти
    {
        public int Id_Сортимент { get; set; }
        public string Сортимент { get; set; }
        public decimal до_0_05 { get; set; }
        public decimal C0_06_0_08 { get; set; }
        public decimal C0_09_0_12 { get; set; }
        public decimal C0_13_0_22 { get; set; }
        public decimal C0_23_0_36 { get; set; }
        public decimal C0_37_0_54 { get; set; }
        public decimal C0_55_0_76 { get; set; }
        public decimal C0_77_1_02 { get; set; }
        public decimal C1_03_1_29 { get; set; }
        public decimal C1_30_1_61 { get; set; }
    }
}
