//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Догляд_за_л_к_мотокущорізом
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Догляд_за_л_к_мотокущорізом()
        {
            this.Догляд_за_л_к_мотокущорізом_Норма = new HashSet<Догляд_за_л_к_мотокущорізом_Норма>();
            this.Догляд_за_л_к_мотокущорізом_ГСМ = new HashSet<Догляд_за_л_к_мотокущорізом_ГСМ>();
        }
    
        public int Id_Вид_робіт { get; set; }
        public string Вид_робіт { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Догляд_за_л_к_мотокущорізом_Норма> Догляд_за_л_к_мотокущорізом_Норма { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Догляд_за_л_к_мотокущорізом_ГСМ> Догляд_за_л_к_мотокущорізом_ГСМ { get; set; }
    }
}
