//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рубки_догляду_за_лісом_ПРЖ_ПРХ_ВСР_Норма
    {
        public int Вид_робітID { get; set; }
        public int Вид_робіт { get; set; }
        public decimal C0_035 { get; set; }
        public decimal C0_04 { get; set; }
        public decimal C0_045 { get; set; }
        public decimal C0_05 { get; set; }
        public decimal C0_055 { get; set; }
        public decimal C0_06 { get; set; }
        public decimal C0_065 { get; set; }
        public decimal C0_07 { get; set; }
        public decimal C0_08 { get; set; }
        public decimal C0_09 { get; set; }
        public decimal C0_1 { get; set; }
        public decimal C0_12 { get; set; }
        public decimal C0_14 { get; set; }
        public decimal C0_16 { get; set; }
        public decimal C0_19 { get; set; }
        public decimal C0_22 { get; set; }
        public decimal C0_25 { get; set; }
        public decimal C0_29 { get; set; }
        public decimal C0_35 { get; set; }
        public decimal C0_41 { get; set; }
        public decimal C0_5 { get; set; }
        public decimal C0_62 { get; set; }
        public decimal C0_78 { get; set; }
        public decimal C0_98 { get; set; }
        public decimal C1_5 { get; set; }
    
        public virtual Рубки_догляду_за_лісом_ПРЖ_ПРХ_ВСР Рубки_догляду_за_лісом_ПРЖ_ПРХ_ВСР { get; set; }
    }
}
