//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Трелювання_РУ_ГСМ
    {
        public int Вид_робітID { get; set; }
        public int Вид_робіт { get; set; }
        public decimal C0_1 { get; set; }
        public decimal C0_12 { get; set; }
        public decimal C0_14 { get; set; }
        public decimal C0_16 { get; set; }
        public decimal C0_18 { get; set; }
        public decimal C0_21 { get; set; }
        public decimal C0_24 { get; set; }
        public decimal C0_28 { get; set; }
        public decimal C0_34 { get; set; }
        public decimal C0_4 { get; set; }
        public decimal C0_49 { get; set; }
        public decimal C0_61 { get; set; }
        public decimal C0_77 { get; set; }
        public decimal C0_97 { get; set; }
        public decimal C1_5 { get; set; }
    
        public virtual Трелювання_РУ Трелювання_РУ { get; set; }
    }
}
