//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Наряд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Трелювання_фанери_РУ_ГСМ
    {
        public int Вид_робітID { get; set; }
        public int Вид_робіт { get; set; }
        public decimal C0_1 { get; set; }
        public decimal C0_12 { get; set; }
        public decimal C0_14 { get; set; }
        public decimal C0_16 { get; set; }
        public decimal C0_19 { get; set; }
        public decimal C0_22 { get; set; }
        public decimal C0_25 { get; set; }
        public decimal C0_29 { get; set; }
        public decimal C0_35 { get; set; }
        public decimal C0_41 { get; set; }
        public decimal C0_5 { get; set; }
        public decimal C0_62 { get; set; }
        public decimal C0_79 { get; set; }
        public decimal C1 { get; set; }
        public decimal C1_5 { get; set; }
    
        public virtual Трелювання_фанери_РУ Трелювання_фанери_РУ { get; set; }
    }
}
